---
- become: false
  collections:
    - kubernetes.core
  hosts: localhost
  tasks:
    - name: Create Namespace
      k8s:
        kubeconfig: ~/kubeconfig
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "keepup-test"
            labels:
              name: keepup
    - name: Create secret
      k8s:
        kubeconfig: ~/kubeconfig
        state: present
        definition:
          apiVersion: v1
          data:
            .dockerconfigjson: ewoiYXV0aHMiOnsiZG9ja2VyOjUwMDAiOnsidXNlcm5hbWUiOiJqZW5raW5zIiwicGFzc3dvcmQiOiJlb242bGVsODQiLCJlbWFpbCI6ImluZm9AdHJhbnMtaXQucHJvIiwiYXV0aCI6ImFtVnVhMmx1Y3pwbGIyNDJiR1ZzT0RRPSJ9fSwKImluc2VjdXJlLXJlZ2lzdHJpZXMiIDogWyJkb2NrZXI6NTAwMCJdCn0K
          kind: Secret
          metadata:
            name: regcred
            namespace: keepup-test
          type: kubernetes.io/dockerconfigjson
    - name: Create KeepUP deployment
      k8s:
        kubeconfig: ~/kubeconfig
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "keepup-base-app"
            namespace: keepup-test
            labels:
              app: keepup-jenkins
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: keepup-jenkins
            template:
              metadata:
                labels:
                  app: keepup-jenkins
              spec:
                containers:
                - name: keepup-jenkins
                  image: fsergeev/keepup-base-app:healthcheck-01
                  imagePullPolicy: Always
                  resources:
                    requests:
                      memory: "512Mi"
                      cpu: "250m"
                    limits:
                      memory: "1024Mi"
                      cpu: "500m"
                imagePullSecrets:
                - name: regcred
    - name: Create service
      k8s:
        kubeconfig: ~/kubeconfig
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: keepup-app-service
            namespace: keepup-test
          spec:
            type: NodePort
            selector:
              app: keepup-jenkins
            ports:
              - port: 8080
                targetPort: 8080
                nodePort: 30080
    - name: Create ingress
      k8s:
        kubeconfig: ~/kubeconfig
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: keepup-ingress
            namespace: keepup-test
            annotations:
              kubernetes.io/ingress.class: public
          spec:
            rules:
            - host: "microk8s-node-0"
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: keepup-app-service
                      port:
                        number: 8080

    - name: Create mock server deployment
      k8s:
        kubeconfig: ~/kubeconfig
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "mock-server"
            namespace: keepup-test
            labels:
              app: mock-server
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: mock-server
            template:
              metadata:
                labels:
                  app: mock-server
              spec:
                containers:
                - name: mock-server
                  image: docker:5000/keepup/mock-server:master
                  imagePullPolicy: Always
                  resources:
                    requests:
                      memory: "512Mi"
                      cpu: "100m"
                    limits:
                      memory: "512Mi"
                      cpu: "200m"
                imagePullSecrets:
                - name: regcred

    - name: Create mock server service
      k8s:
        kubeconfig: ~/kubeconfig
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: mock-service
            namespace: keepup-test
          spec:
            type: NodePort
            selector:
              app: mock-server
            ports:
              - port: 8080
                targetPort: 8080
                nodePort: 30083